version: "1"
rules:
  - base: upstream_master
    upstream: Dreamacro:master
    mergeMethod: hardreset
  - base: master
    upstream: upstream_master
  - base: upstream_dev
    upstream: Dreamacro:dev
    mergeMethod: hardreset
  - base: master
    upstream: upstream_dev
label: ":arrow_heading_down: pull"
